spring.application.name=ejercicio10
# ?? Conexión a la base de datos ??????????????????????????????????
spring.datasource.url=jdbc:postgresql://dpg-d8ccq6po3t8c739rs4u0-a.oregon-postgres.render.com:5432/bd_prog4_ejercicio10
zone=UTC
spring.datasource.username=bd_prog4_ejercicio10_user
spring.datasource.password=Kw0GgAFMbJLaFJtvaUQU1U4qCJb3PBLx
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Imprime el SQL en consola (solo desarrollo)
spring.jpa.properties.hibernate.format_sql=true
